---
- name: Install NGINX on all webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Update APT packages (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install NGINX (Ubuntu/Debian)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install NGINX (Amazon Linux/RedHat)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
